### ISSUE TITLE
博主做的挺好的

### ISSUE THREAD

**Issue by owenzjg** [gutalk-website/issue-repo#17]
博主做的挺好的，喜欢，[我也做了一个个人博客](https://owenzjg.netlify.app/)可以互相交流一下

**Comment by xgugugu** [comment]
然而，这并不是一个个人博客......

**Comment by owenzjg** [comment]
为什么不是个人博客？

**Comment by owenzjg** [comment]
还有可以帮我做一个像你这样的网站吗

**Comment by owenzjg** [comment]
我准备给我的网站加一个讨论总板

**Comment by xgugugu** [comment]
源码在github仓库，你可以自己去看：

https://github.com/gutalk-website/gu-talk
