### ISSUE TITLE
Linux系列（1）

### ISSUE THREAD

**Issue by xgugugu** [gutalk-website/issue-repo#20]
### 什么是Linux

Linux是一种免费使用和自由传播的类UNIX操作系统。广义上的Linux泛指所有基于Linux内核的操作系统，而狭义的Linux指Linux内核。Linux有上百种不同的发行版，如Debian、Red Hat、Arch Linux等。

Linux是现在最流行的操作系统内核，广泛应用于嵌入式、移动设备等领域。知名的Android操作系统就是基于Linux内核。

### Linux的特点

1. 一切皆文件：任何命令、设备、进程都被抽象为文件，可以使用文件操作的API来方便的操作，这就使得Linux的API数量非常精简。
2. 完全自由：Linux是一款自由免费的操作系统，用户可以免费获得，并可以任意修改其源代码，这就使得Linux的社区非常庞大，能够集思广益，不断发展。
3. 多任务、多用户：Linux支持多用户，各个用户对于自己的文件设备有自己特殊的权利，保证了各用户之间互不影响。多任务则是现代电脑最主要的一个特点，Linux可以使多个程序同时并独立地运行。
4. 良好的界面：不同于商业开发的Windows、macOS，Linux的界面完全由社区维护，有很高的自定义性，不仅可以使用字符界面和完整的桌面环境，还可以从窗口管理器开始配置自己的桌面。
5. 多平台：Linux可以运行在多种硬件平台上，如x86、arm等。

### Linux图形界面

作为普通用户，肯定不能整天用个字符界面过日子，要有一个好用的图形界面才行。目前Linux有三大桌面环境，是GNOME、KDE、Xfce，都有各自的特点。GNOME类似mac风格，KDE与Windows相似，Xfce则主打轻量级。主流的Linux发行版基本都自带桌面环境。

**Comment by WP-Studio01** [comment]
额，我要看

**Comment by BaoSiYuanCODE** [comment]
要看啊
