### ISSUE TITLE
【已弃坑】Gutalk 新版正在开发中！

### ISSUE THREAD

**Issue by xgugugu** [gutalk-website/issue-repo#26]
# 本项目已经弃坑

> 由于原版Gutalk架构混乱，维护困难，现决定使用新的工具链重新编写

新版预览链接：<https://gutalk-dev.netlify.app/>

你可以在这里参与贡献：<https://github.com/xgugugu/gutalk>

![](https://cdn.jsdelivr.net/gh/xgugugu/xgugugu@main/img/0.07945476732826884)

**Comment by 20AHXA10** [comment]
js什么的都不会能参与贡献吗（

**Comment by xgugugu** [comment]
![](https://cdn.jsdelivr.net/gh/xgugugu/xgugugu@main/img/0.24144462780989495)
